version: '3.7'
services:
  postgres:
    image: postgres:11.2
    command: postgres -c 'max_connections=600' -c log_statement=all
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 55432:5432